version: '3'
services:
  tf:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ../../wheels:/wheels
    environment:
      - TF_VERSION_GIT_TAG=v1.8.0
      - PYTHON_VERSION=3.5
      - USE_GPU=1
      - CUDA_VERSION=9.2
      - CUDNN_VERSION=7.1.3
